# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            TheDramatist
tagline:          'Web Programmer'
description:      'A self-taught guy who writes poetry with code. Love to solve problems. PHP and WordPress enthusiastic. StackExchange and GitHub contributor. Plus TheMarsSociety volunteer.'
url:              http://www.thedramatist.me
baseurl:          http://www.thedramatist.me/
# baseurl:          http://rnaby.github.io/

author:
  name:           'Khan M Rashedun-Naby'
  url:            https://twitter.com/rnaby

paginate:         5
paginate_path:    'blog/page:num/'

plugins:
  - jekyll-seo-tag

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/rnaby
