# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            TheDramatist
tagline:          'Web Programmer'
description:      'A self-taught guy who writes poetry with code. Keen to learn new things. And always ready to contribute as well as help or support.'
url:              http://rnaby.github.io
baseurl:          http://rnaby.github.io/

author:
  name:           'Khan M Rashedun-Naby'
  url:            https://twitter.com/rnaby

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/rnaby
