# Dependencies
markdown:         kramdown #redcarpet
highlighter:      rouge

# Permalinks
permalink:        /:year/:month/:day/:title

# Setup
title:            CodeMascot
tagline:          'A self taught reader who loves to solve problems'
description:      'A self-taught reader who loves to solve problems. Philosophy, Non-Fiction and History enthusiastic. Contributed to several open source softwares. Very keen to learn new things.'
baseurl:          https://www.codemascot.com/
url:              https://www.codemascot.com/
google_verify:    at9Eb_8UWPXn39jSyjV4IJwm6szkk6SIfJosUVX_xlo

author:
  name:           'Khan Mohammad R.'
  url:            https://www.linkedin.com/in/codemascot/

paginate:         3
paginate_path:    '/blog/:num/'

kramdown:
  # use Github Flavored Markdown
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  # do not replace newlines by <br>s
  hard_wrap: false

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - kramdown
  - rouge

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/codemascot
